// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationsFieldNames          = builder.RawFieldNames(&Conversations{})
	conversationsRows                = strings.Join(conversationsFieldNames, ",")
	conversationsRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	conversationsRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAichatChatDbConversationsIdPrefix        = "cache:aichatChatDb:conversations:id:"
	cacheAichatChatDbConversationsSessionIdPrefix = "cache:aichatChatDb:conversations:sessionId:"
)

type (
	conversationsModel interface {
		Insert(ctx context.Context, data *Conversations) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Conversations, error)
		FindOneBySessionId(ctx context.Context, sessionId string) (*Conversations, error)
		Update(ctx context.Context, data *Conversations) error
		Delete(ctx context.Context, id int64) error
	}

	defaultConversationsModel struct {
		sqlc.CachedConn
		table string
	}

	Conversations struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"`    // 用户ID
		SessionId string    `db:"session_id"` // 同一话题的id
		Title     string    `db:"title"`      // 会话标题
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newConversationsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultConversationsModel {
	return &defaultConversationsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`conversations`",
	}
}

func (m *defaultConversationsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aichatChatDbConversationsIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsIdPrefix, id)
	aichatChatDbConversationsSessionIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsSessionIdPrefix, data.SessionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aichatChatDbConversationsIdKey, aichatChatDbConversationsSessionIdKey)
	return err
}

func (m *defaultConversationsModel) FindOne(ctx context.Context, id int64) (*Conversations, error) {
	aichatChatDbConversationsIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsIdPrefix, id)
	var resp Conversations
	err := m.QueryRowCtx(ctx, &resp, aichatChatDbConversationsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationsModel) FindOneBySessionId(ctx context.Context, sessionId string) (*Conversations, error) {
	aichatChatDbConversationsSessionIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsSessionIdPrefix, sessionId)
	var resp Conversations
	err := m.QueryRowIndexCtx(ctx, &resp, aichatChatDbConversationsSessionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", conversationsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, sessionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationsModel) Insert(ctx context.Context, data *Conversations) (sql.Result, error) {
	aichatChatDbConversationsIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsIdPrefix, data.Id)
	aichatChatDbConversationsSessionIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsSessionIdPrefix, data.SessionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, conversationsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.SessionId, data.Title)
	}, aichatChatDbConversationsIdKey, aichatChatDbConversationsSessionIdKey)
	return ret, err
}

func (m *defaultConversationsModel) Update(ctx context.Context, newData *Conversations) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aichatChatDbConversationsIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsIdPrefix, data.Id)
	aichatChatDbConversationsSessionIdKey := fmt.Sprintf("%s%v", cacheAichatChatDbConversationsSessionIdPrefix, data.SessionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, conversationsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.SessionId, newData.Title, newData.Id)
	}, aichatChatDbConversationsIdKey, aichatChatDbConversationsSessionIdKey)
	return err
}

func (m *defaultConversationsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAichatChatDbConversationsIdPrefix, primary)
}

func (m *defaultConversationsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultConversationsModel) tableName() string {
	return m.table
}
