@buildDir = "build"

app/ai/rpc/**/*.go {
    prep: go build -o ./build/ai-rpc.exe ./app/ai/rpc/ai.go
    daemon +sigkill: ./build/ai-rpc.exe -f ./app/ai/rpc/etc/ai.yaml
}

app/gateway/api/**/*.go {
    prep: go build -o ./build/gateway-api.exe ./app/gateway/api/gateway.go
    daemon +sigkill: ./build/gateway-api.exe -f ./app/gateway/api/etc/gateway.yaml
}

app/user/rpc/**/*.go {
    prep: go build -o ./build/user-rpc.exe ./app/user/rpc/user.go
    daemon +sigkill: ./build/user-rpc.exe -f ./app/user/rpc/etc/user.yaml
}

# # Python RAG 服务（使用 uvicorn 热重载）
# app/ragservice/**/*.py {
#     # 激活 conda 环境并启动 uvicorn 服务，开启热重载，监听 8082 端口
#     daemon +sigkill: (D:\Softwars\Anaconda\shell\condabin\conda-hook.ps1) ; (conda activate aiChatRAG) ; cd app/ragservice/embedding-service && uvicorn main:app --reload --host 0.0.0.0 --port 8082
# }