// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.3
// source: ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiRpc_Chat_FullMethodName = "/ai.AiRpc/Chat"
)

// AiRpcClient is the client API for AiRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiRpc 服务定义
type AiRpcClient interface {
	// Chat 对话接口
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type aiRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAiRpcClient(cc grpc.ClientConnInterface) AiRpcClient {
	return &aiRpcClient{cc}
}

func (c *aiRpcClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AiRpc_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiRpcServer is the server API for AiRpc service.
// All implementations must embed UnimplementedAiRpcServer
// for forward compatibility.
//
// AiRpc 服务定义
type AiRpcServer interface {
	// Chat 对话接口
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedAiRpcServer()
}

// UnimplementedAiRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiRpcServer struct{}

func (UnimplementedAiRpcServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiRpcServer) mustEmbedUnimplementedAiRpcServer() {}
func (UnimplementedAiRpcServer) testEmbeddedByValue()               {}

// UnsafeAiRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiRpcServer will
// result in compilation errors.
type UnsafeAiRpcServer interface {
	mustEmbedUnimplementedAiRpcServer()
}

func RegisterAiRpcServer(s grpc.ServiceRegistrar, srv AiRpcServer) {
	// If the following call panics, it indicates UnimplementedAiRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiRpc_ServiceDesc, srv)
}

func _AiRpc_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRpcServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRpc_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRpcServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiRpc_ServiceDesc is the grpc.ServiceDesc for AiRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiRpc",
	HandlerType: (*AiRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _AiRpc_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
