// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package airpc

import (
	"context"

	"aiChat/app/ai/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatRequest      = pb.ChatRequest
	ChatResponse     = pb.ChatResponse
	Choice           = pb.Choice
	DeepSeekResponse = pb.DeepSeekResponse
	Message          = pb.Message
	Usage            = pb.Usage

	AiRpc interface {
		// Chat 对话接口
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	}

	defaultAiRpc struct {
		cli zrpc.Client
	}
)

func NewAiRpc(cli zrpc.Client) AiRpc {
	return &defaultAiRpc{
		cli: cli,
	}
}

// Chat 对话接口
func (m *defaultAiRpc) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := pb.NewAiRpcClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}
