// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package server

import (
	"context"

	"aiChat/app/ai/rpc/internal/logic"
	"aiChat/app/ai/rpc/internal/svc"
	"aiChat/app/ai/rpc/pb"
)

type AiRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiRpcServer
}

func NewAiRpcServer(svcCtx *svc.ServiceContext) *AiRpcServer {
	return &AiRpcServer{
		svcCtx: svcCtx,
	}
}

// Chat 对话接口
func (s *AiRpcServer) Chat(ctx context.Context, in *pb.ChatRequest) (*pb.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}
