// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatReq struct {
	Message   string `json:"message"`
	SessionId string `json:"session_id"`
}

type ChatResp struct {
	Reply     string `json:"reply"`
	SessionId string `json:"session_id"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
}
